/* WARNING: This file is auto-generated. Do not modify manually. */

#ifndef SLATEDB_C_H
#define SLATEDB_C_H

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum slatedb_error_t {
    SLATEDB_SUCCESS = 0,
    SLATEDB_INVALID_ARGUMENT = 1,
    SLATEDB_NULL_POINTER = 2,
    SLATEDB_INVALID_HANDLE = 3,
    SLATEDB_TRANSACTION = 4,
    SLATEDB_CLOSED = 5,
    SLATEDB_UNAVAILABLE = 6,
    SLATEDB_INVALID = 7,
    SLATEDB_DATA = 8,
    SLATEDB_INTERNAL = 9,
} slatedb_error_t;

typedef struct slatedb_db_builder_t slatedb_db_builder_t;

typedef struct slatedb_db_t slatedb_db_t;

typedef struct slatedb_iterator_t slatedb_iterator_t;

typedef struct slatedb_object_store_t slatedb_object_store_t;

typedef struct slatedb_write_batch_t slatedb_write_batch_t;

typedef struct slatedb_result_t {
    enum slatedb_error_t error;
    bool none;
    char *message;
} slatedb_result_t;

typedef uint8_t slatedb_sst_block_size_t;

typedef struct slatedb_value_t {
    uint8_t *data;
    uintptr_t len;
} slatedb_value_t;

typedef struct slatedb_read_options_t {
    uint8_t durability_filter;
    bool dirty;
    bool cache_blocks;
} slatedb_read_options_t;

typedef struct slatedb_put_options_t {
    uint8_t ttl_type;
    uint64_t ttl_value;
} slatedb_put_options_t;

typedef struct slatedb_write_options_t {
    bool await_durable;
} slatedb_write_options_t;

typedef struct slatedb_merge_options_t {
    uint8_t ttl_type;
    uint64_t ttl_value;
} slatedb_merge_options_t;

typedef struct slatedb_bound_t {
    uint8_t kind;
    const uint8_t *data;
    uintptr_t len;
} slatedb_bound_t;

typedef struct slatedb_range_t {
    struct slatedb_bound_t start;
    struct slatedb_bound_t end;
} slatedb_range_t;

typedef struct slatedb_scan_options_t {
    uint8_t durability_filter;
    bool dirty;
    uint64_t read_ahead_bytes;
    bool cache_blocks;
    uint64_t max_fetch_tasks;
} slatedb_scan_options_t;

typedef struct slatedb_flush_options_t {
    uint8_t flush_type;
} slatedb_flush_options_t;

typedef struct slatedb_key_value_t {
    struct slatedb_value_t key;
    struct slatedb_value_t value;
} slatedb_key_value_t;

// # Safety
// - `path` must be a valid C string.
// - `object_store` must be a valid object store handle.
// - `out_db` must be non-null.
struct slatedb_result_t slatedb_db_open(const char *path,
                                        const struct slatedb_object_store_t *object_store,
                                        struct slatedb_db_t **out_db);

// # Safety
// - `path` must be a valid C string.
// - `object_store` must be a valid object store handle.
// - `out_builder` must be non-null.
struct slatedb_result_t slatedb_db_builder_new(const char *path,
                                               const struct slatedb_object_store_t *object_store,
                                               struct slatedb_db_builder_t **out_builder);

struct slatedb_result_t slatedb_db_builder_with_wal_object_store(struct slatedb_db_builder_t *builder,
                                                                 const struct slatedb_object_store_t *wal_object_store);

struct slatedb_result_t slatedb_db_builder_with_seed(struct slatedb_db_builder_t *builder,
                                                     uint64_t seed);

struct slatedb_result_t slatedb_db_builder_with_sst_block_size(struct slatedb_db_builder_t *builder,
                                                               slatedb_sst_block_size_t sst_block_size);

// Consumes the builder, matching `DbBuilder::build(self)` semantics.
struct slatedb_result_t slatedb_db_builder_build(struct slatedb_db_builder_t *builder,
                                                 struct slatedb_db_t **out_db);

struct slatedb_result_t slatedb_db_builder_close(struct slatedb_db_builder_t *builder);

struct slatedb_result_t slatedb_db_status(const struct slatedb_db_t *db);

struct slatedb_result_t slatedb_db_get(struct slatedb_db_t *db,
                                       const uint8_t *key,
                                       uintptr_t key_len,
                                       struct slatedb_value_t *out_value);

struct slatedb_result_t slatedb_db_get_with_options(struct slatedb_db_t *db,
                                                    const uint8_t *key,
                                                    uintptr_t key_len,
                                                    const struct slatedb_read_options_t *read_options,
                                                    struct slatedb_value_t *out_value);

struct slatedb_result_t slatedb_db_put(struct slatedb_db_t *db,
                                       const uint8_t *key,
                                       uintptr_t key_len,
                                       const uint8_t *value,
                                       uintptr_t value_len);

struct slatedb_result_t slatedb_db_put_with_options(struct slatedb_db_t *db,
                                                    const uint8_t *key,
                                                    uintptr_t key_len,
                                                    const uint8_t *value,
                                                    uintptr_t value_len,
                                                    const struct slatedb_put_options_t *put_options,
                                                    const struct slatedb_write_options_t *write_options);

struct slatedb_result_t slatedb_db_delete(struct slatedb_db_t *db,
                                          const uint8_t *key,
                                          uintptr_t key_len);

struct slatedb_result_t slatedb_db_delete_with_options(struct slatedb_db_t *db,
                                                       const uint8_t *key,
                                                       uintptr_t key_len,
                                                       const struct slatedb_write_options_t *write_options);

struct slatedb_result_t slatedb_db_merge(struct slatedb_db_t *db,
                                         const uint8_t *key,
                                         uintptr_t key_len,
                                         const uint8_t *value,
                                         uintptr_t value_len);

struct slatedb_result_t slatedb_db_merge_with_options(struct slatedb_db_t *db,
                                                      const uint8_t *key,
                                                      uintptr_t key_len,
                                                      const uint8_t *value,
                                                      uintptr_t value_len,
                                                      const struct slatedb_merge_options_t *merge_options,
                                                      const struct slatedb_write_options_t *write_options);

struct slatedb_result_t slatedb_db_write(struct slatedb_db_t *db,
                                         struct slatedb_write_batch_t *write_batch);

struct slatedb_result_t slatedb_db_write_with_options(struct slatedb_db_t *db,
                                                      struct slatedb_write_batch_t *write_batch,
                                                      const struct slatedb_write_options_t *write_options);

struct slatedb_result_t slatedb_db_scan(struct slatedb_db_t *db,
                                        struct slatedb_range_t range,
                                        struct slatedb_iterator_t **out_iterator);

struct slatedb_result_t slatedb_db_scan_with_options(struct slatedb_db_t *db,
                                                     struct slatedb_range_t range,
                                                     const struct slatedb_scan_options_t *scan_options,
                                                     struct slatedb_iterator_t **out_iterator);

struct slatedb_result_t slatedb_db_scan_prefix(struct slatedb_db_t *db,
                                               const uint8_t *prefix,
                                               uintptr_t prefix_len,
                                               struct slatedb_iterator_t **out_iterator);

struct slatedb_result_t slatedb_db_scan_prefix_with_options(struct slatedb_db_t *db,
                                                            const uint8_t *prefix,
                                                            uintptr_t prefix_len,
                                                            const struct slatedb_scan_options_t *scan_options,
                                                            struct slatedb_iterator_t **out_iterator);

struct slatedb_result_t slatedb_db_flush(struct slatedb_db_t *db);

struct slatedb_result_t slatedb_db_flush_with_options(struct slatedb_db_t *db,
                                                      const struct slatedb_flush_options_t *flush_options);

// Closes and frees the DB handle.
struct slatedb_result_t slatedb_db_close(struct slatedb_db_t *db);

struct slatedb_result_t slatedb_iterator_next(struct slatedb_iterator_t *iterator,
                                              struct slatedb_key_value_t *out_key_value);

struct slatedb_result_t slatedb_iterator_seek(struct slatedb_iterator_t *iterator,
                                              const uint8_t *key,
                                              uintptr_t key_len);

struct slatedb_result_t slatedb_iterator_close(struct slatedb_iterator_t *iterator);

void slatedb_result_free(struct slatedb_result_t result);

void slatedb_value_free(struct slatedb_value_t value);

void slatedb_key_value_free(struct slatedb_key_value_t key_value);

// Resolve an object store using `Db::resolve_object_store`.
//
// # Safety
// - `url` must be a valid, null-terminated C string.
// - `out_object_store` must be non-null.
struct slatedb_result_t slatedb_db_resolve_object_store(const char *url,
                                                        struct slatedb_object_store_t **out_object_store);

struct slatedb_result_t slatedb_object_store_close(struct slatedb_object_store_t *object_store);

struct slatedb_result_t slatedb_write_batch_new(struct slatedb_write_batch_t **out_write_batch);

struct slatedb_result_t slatedb_write_batch_put(struct slatedb_write_batch_t *write_batch,
                                                const uint8_t *key,
                                                uintptr_t key_len,
                                                const uint8_t *value,
                                                uintptr_t value_len);

struct slatedb_result_t slatedb_write_batch_put_with_options(struct slatedb_write_batch_t *write_batch,
                                                             const uint8_t *key,
                                                             uintptr_t key_len,
                                                             const uint8_t *value,
                                                             uintptr_t value_len,
                                                             const struct slatedb_put_options_t *put_options);

struct slatedb_result_t slatedb_write_batch_merge(struct slatedb_write_batch_t *write_batch,
                                                  const uint8_t *key,
                                                  uintptr_t key_len,
                                                  const uint8_t *value,
                                                  uintptr_t value_len);

struct slatedb_result_t slatedb_write_batch_merge_with_options(struct slatedb_write_batch_t *write_batch,
                                                               const uint8_t *key,
                                                               uintptr_t key_len,
                                                               const uint8_t *value,
                                                               uintptr_t value_len,
                                                               const struct slatedb_merge_options_t *merge_options);

struct slatedb_result_t slatedb_write_batch_delete(struct slatedb_write_batch_t *write_batch,
                                                   const uint8_t *key,
                                                   uintptr_t key_len);

struct slatedb_result_t slatedb_write_batch_close(struct slatedb_write_batch_t *write_batch);

#endif  /* SLATEDB_C_H */
