use std::collections::{BTreeMap, BTreeSet};
use std::sync::atomic::{AtomicU64, Ordering};

use async_trait::async_trait;
use bytes::Bytes;
use log::info;
use rand::RngCore;
use slatedb::config::{
    DurabilityLevel, MergeOptions, PutOptions, ReadOptions, ScanOptions, WriteOptions,
};
use slatedb::{Error, MergeOperator, MergeOperatorError, WriteBatch};
use tracing::instrument;

use crate::{Actor, ActorCtx};

use super::PROGRESS_LOG_INTERVAL;

const WORKLOAD_VALUE_VERSION_SIZE: usize = std::mem::size_of::<u64>();

/// Configuration for the mixed DST workload actor.
#[derive(Clone, Debug)]
pub struct WorkloadActorOptions {
    /// Number of logical keys each actor maps random samples onto under its
    /// `{name}/` prefix.
    pub key_count: usize,
    /// Minimum random value size generated for `put`, `merge`, and `write_batch`.
    pub min_value_size: usize,
    /// Maximum random value size generated for `put`, `merge`, and `write_batch`.
    pub max_value_size: usize,
    /// Durability level used by workload read verification.
    pub read_durability: DurabilityLevel,
}

impl Default for WorkloadActorOptions {
    fn default() -> Self {
        Self {
            key_count: 1024,
            min_value_size: 32,
            max_value_size: 256,
            read_durability: DurabilityLevel::Memory,
        }
    }
}

/// Merge operator for values generated by [`WorkloadActor`].
///
/// Workload values encode a big-endian `u64` version in the first eight bytes
/// and treat the remaining bytes as opaque payload. Merge operands advance the
/// version while preserving the base payload bytes.
#[derive(Debug, Default)]
pub struct WorkloadMergeOperator;

impl MergeOperator for WorkloadMergeOperator {
    fn merge(
        &self,
        key: &Bytes,
        existing_value: Option<Bytes>,
        value: Bytes,
    ) -> Result<Bytes, MergeOperatorError> {
        self.merge_batch(key, existing_value, std::slice::from_ref(&value))
    }

    fn merge_batch(
        &self,
        _key: &Bytes,
        existing_value: Option<Bytes>,
        operands: &[Bytes],
    ) -> Result<Bytes, MergeOperatorError> {
        let (base_value, version_increment) = match existing_value {
            Some(value) => (
                value,
                u64::try_from(operands.len()).expect("operand count must fit in u64"),
            ),
            None => {
                let Some(first_operand) = operands.first() else {
                    return Err(MergeOperatorError::EmptyBatch);
                };
                (
                    first_operand.clone(),
                    u64::try_from(operands.len() - 1).expect("operand count must fit in u64"),
                )
            }
        };
        let version = decode_workload_value(base_value.as_ref())
            .checked_add(version_increment)
            .expect("workload merge version overflowed");

        Ok(workload_value_with_version(base_value, version))
    }
}

#[derive(Debug)]
pub struct WorkloadActor {
    options: WorkloadActorOptions,
    observed: BTreeMap<Bytes, Observation>,
    next_value_version: AtomicU64,
    step: u64,
    key_prefix: Option<String>,
}

#[derive(Clone, Copy, Debug)]
struct Observation {
    max_seen_version: u64,
    observed_absent: bool,
}

impl WorkloadActor {
    pub fn new(options: WorkloadActorOptions) -> Result<Self, Error> {
        assert!(
            options.key_count > 0,
            "workload actor key_count must be greater than zero"
        );
        assert!(
            options.min_value_size <= options.max_value_size,
            "workload actor min_value_size must be less than or equal to max_value_size"
        );
        assert!(
            options.max_value_size >= WORKLOAD_VALUE_VERSION_SIZE,
            "workload actor max_value_size must be at least {WORKLOAD_VALUE_VERSION_SIZE} bytes"
        );

        Ok(Self {
            options,
            observed: BTreeMap::new(),
            next_value_version: AtomicU64::new(1),
            step: 0,
            key_prefix: None,
        })
    }
}

#[derive(Clone, Copy, Debug)]
enum WorkloadOperation {
    Get,
    Scan,
    Delete,
    Put,
    Merge,
    WriteBatch,
}

impl WorkloadOperation {
    fn sample(rand_value: u64, merge_enabled: bool) -> Self {
        if merge_enabled {
            match rand_value % 6 {
                0 => Self::Get,
                1 => Self::Scan,
                2 => Self::Delete,
                3 => Self::Put,
                4 => Self::Merge,
                _ => Self::WriteBatch,
            }
        } else {
            match rand_value % 5 {
                0 => Self::Get,
                1 => Self::Scan,
                2 => Self::Delete,
                3 => Self::Put,
                _ => Self::WriteBatch,
            }
        }
    }
}

#[async_trait]
impl Actor for WorkloadActor {
    /// Executes one mixed deterministic workload step against the shared
    /// database while verifying reads against actor-local monotonic observations.
    #[instrument(level = "debug", skip_all, fields(name = %ctx.name()))]
    async fn run(&mut self, ctx: &ActorCtx) -> Result<(), Error> {
        let put_options = PutOptions::default();
        let write_options = WriteOptions {
            await_durable: false,
            ..WriteOptions::default()
        };
        let key_prefix = self
            .key_prefix
            .get_or_insert_with(|| format!("{}/", ctx.name()))
            .clone();
        let merge_enabled = ctx.merge_operator().is_some();
        let operation = WorkloadOperation::sample(ctx.rand().rng().next_u64(), merge_enabled);

        match operation {
            WorkloadOperation::Get => {
                let key = workload_key(
                    &key_prefix,
                    ctx.rand().rng().next_u64(),
                    self.options.key_count,
                );
                verify_get(
                    ctx,
                    self.step,
                    &key,
                    self.options.read_durability,
                    &mut self.observed,
                )
                .await?;
            }
            WorkloadOperation::Scan => {
                verify_scan(
                    ctx,
                    self.step,
                    &key_prefix,
                    self.options.read_durability,
                    &mut self.observed,
                )
                .await?;
            }
            WorkloadOperation::Delete => {
                let key = workload_key(
                    &key_prefix,
                    ctx.rand().rng().next_u64(),
                    self.options.key_count,
                );
                ctx.db()
                    .delete_with_options(key.clone(), &write_options)
                    .await?;
            }
            WorkloadOperation::Put => {
                let key = workload_key(
                    &key_prefix,
                    ctx.rand().rng().next_u64(),
                    self.options.key_count,
                );
                let value = self.next_workload_value(ctx);
                ctx.db()
                    .put_with_options(key.clone(), value, &put_options, &write_options)
                    .await?;
            }
            WorkloadOperation::Merge => {
                let key = workload_key(
                    &key_prefix,
                    ctx.rand().rng().next_u64(),
                    self.options.key_count,
                );
                let value = self.next_workload_value(ctx);
                ctx.db()
                    .merge_with_options(
                        key.clone(),
                        value,
                        &MergeOptions::default(),
                        &write_options,
                    )
                    .await?;
            }
            WorkloadOperation::WriteBatch => {
                let mut batch = WriteBatch::new();
                let batch_len = 2 + (ctx.rand().rng().next_u64() % 3) as usize;

                for _ in 0..batch_len {
                    let key = workload_key(
                        &key_prefix,
                        ctx.rand().rng().next_u64(),
                        self.options.key_count,
                    );
                    let sampled_operation_count = if merge_enabled { 3 } else { 2 };
                    let sampled_operation = {
                        let mut rng = ctx.rand().rng();
                        rng.next_u64() % sampled_operation_count
                    };
                    match sampled_operation {
                        0 => {
                            let value = self.next_workload_value(ctx);
                            batch.put_bytes(key.clone(), value);
                        }
                        1 => batch.delete(key.clone()),
                        _ => {
                            let value = self.next_workload_value(ctx);
                            batch.merge(key.clone(), value);
                        }
                    }
                }

                ctx.db().write_with_options(batch, &write_options).await?;
            }
        }

        self.step += 1;
        if self.step % PROGRESS_LOG_INTERVAL == 0 {
            info!(
                "workload step complete [name={}, step={}, observed_keys={}]",
                ctx.name(),
                self.step,
                self.observed.len()
            );
        }

        Ok(())
    }
}

impl WorkloadActor {
    fn next_workload_value(&self, ctx: &ActorCtx) -> Bytes {
        let version = self.next_value_version.fetch_add(1, Ordering::Relaxed);
        workload_value(
            version,
            &mut *ctx.rand().rng(),
            self.options.min_value_size,
            self.options.max_value_size,
        )
    }
}

fn workload_key(prefix: &str, rand_value: u64, key_count: usize) -> Bytes {
    let key_index = ((rand_value >> 8) as usize) % key_count;
    Bytes::from(format!("{prefix}{key_index}"))
}

fn workload_value(
    version: u64,
    rng: &mut impl RngCore,
    min_value_size: usize,
    max_value_size: usize,
) -> Bytes {
    let min_value_size = min_value_size.max(WORKLOAD_VALUE_VERSION_SIZE);
    let value_len =
        min_value_size + (rng.next_u64() as usize % (max_value_size - min_value_size + 1));
    let mut value = vec![0; value_len];
    value[..WORKLOAD_VALUE_VERSION_SIZE].copy_from_slice(&version.to_be_bytes());
    rng.fill_bytes(&mut value[WORKLOAD_VALUE_VERSION_SIZE..]);
    Bytes::from(value)
}

fn workload_value_with_version(value: Bytes, version: u64) -> Bytes {
    let mut value = value.to_vec();
    value[..WORKLOAD_VALUE_VERSION_SIZE].copy_from_slice(&version.to_be_bytes());
    Bytes::from(value)
}

async fn verify_get(
    ctx: &ActorCtx,
    step: u64,
    key: &Bytes,
    read_durability: DurabilityLevel,
    observed: &mut BTreeMap<Bytes, Observation>,
) -> Result<(), Error> {
    let read_options = ReadOptions::new().with_durability_filter(read_durability);
    match ctx
        .db()
        .get_with_options(key.clone(), &read_options)
        .await?
    {
        Some(value) => observe_present(ctx, step, key, &value, observed),
        None => observe_absent(key, observed),
    }
    Ok(())
}

async fn verify_scan(
    ctx: &ActorCtx,
    step: u64,
    key_prefix: &str,
    read_durability: DurabilityLevel,
    observed: &mut BTreeMap<Bytes, Observation>,
) -> Result<(), Error> {
    let scan_options = ScanOptions::new().with_durability_filter(read_durability);
    let mut iter = ctx
        .db()
        .scan_prefix_with_options(key_prefix.as_bytes(), &scan_options)
        .await?;
    let mut seen = BTreeSet::new();

    while let Some(key_value) = iter.next().await? {
        assert!(
            key_value.key.starts_with(key_prefix.as_bytes()),
            "workload scan returned key outside prefix [name={}, step={}, key_prefix={}, key={}]",
            ctx.name(),
            step,
            key_prefix,
            String::from_utf8_lossy(key_value.key.as_ref()).into_owned(),
        );
        assert!(
            seen.insert(key_value.key.clone()),
            "workload scan returned duplicate key [name={}, step={}, key_prefix={}, key={}]",
            ctx.name(),
            step,
            key_prefix,
            String::from_utf8_lossy(key_value.key.as_ref()).into_owned(),
        );
        observe_present(ctx, step, &key_value.key, &key_value.value, observed);
    }

    let missing_keys = observed
        .keys()
        .filter(|key| key.starts_with(key_prefix.as_bytes()) && !seen.contains(*key))
        .cloned()
        .collect::<Vec<_>>();
    for key in missing_keys {
        observe_absent(&key, observed);
    }

    Ok(())
}

fn observe_present(
    ctx: &ActorCtx,
    step: u64,
    key: &Bytes,
    value: &Bytes,
    observed: &mut BTreeMap<Bytes, Observation>,
) {
    let version = decode_workload_value(value.as_ref());
    let key_display = String::from_utf8_lossy(key.as_ref()).into_owned();
    match observed.get_mut(key) {
        Some(observation) => {
            assert!(
                !(observation.observed_absent && version <= observation.max_seen_version),
                "workload read stale value after observed deletion [name={}, step={}, key={}, version={}, max_seen_version={}]",
                ctx.name(),
                step,
                key_display,
                version,
                observation.max_seen_version,
            );
            assert!(
                version >= observation.max_seen_version,
                "workload read version moved backward [name={}, step={}, key={}, version={}, max_seen_version={}]",
                ctx.name(),
                step,
                key_display,
                version,
                observation.max_seen_version,
            );
            observation.max_seen_version = version;
            observation.observed_absent = false;
        }
        None => {
            observed.insert(
                key.clone(),
                Observation {
                    max_seen_version: version,
                    observed_absent: false,
                },
            );
        }
    }
}

fn observe_absent(key: &Bytes, observed: &mut BTreeMap<Bytes, Observation>) {
    if let Some(observation) = observed.get_mut(key) {
        observation.observed_absent = true;
    }
}

fn decode_workload_value(value: &[u8]) -> u64 {
    let version_bytes: [u8; WORKLOAD_VALUE_VERSION_SIZE] = value[..WORKLOAD_VALUE_VERSION_SIZE]
        .try_into()
        .expect("workload value version slice has fixed size");
    u64::from_be_bytes(version_bytes)
}
