version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    rust: '1.82'
  jobs:
    post_install:
      - cd bindings/python && VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m maturin develop

sphinx:
  configuration: bindings/python/docs/conf.py

python:
  install:
    - requirements: bindings/python/docs/requirements.txt
