

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOG_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOG_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceLogCallbackMethod0)(uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLogCallbackMethod0(
				UniffiCallbackInterfaceLogCallbackMethod0 cb, uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, record, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_MERGE_OPERATOR_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_MERGE_OPERATOR_METHOD0
typedef void (*UniffiCallbackInterfaceMergeOperatorMethod0)(uint64_t uniffi_handle, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceMergeOperatorMethod0(
				UniffiCallbackInterfaceMergeOperatorMethod0 cb, uint64_t uniffi_handle, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, key, existing_value, operand, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOG_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOG_CALLBACK
typedef struct UniffiVTableCallbackInterfaceLogCallback {
    UniffiCallbackInterfaceLogCallbackMethod0 log;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceLogCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_MERGE_OPERATOR
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_MERGE_OPERATOR
typedef struct UniffiVTableCallbackInterfaceMergeOperator {
    UniffiCallbackInterfaceMergeOperatorMethod0 merge;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceMergeOperator;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DB
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DB
void* uniffi_slatedb_ffi_fn_clone_db(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DB
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DB
void uniffi_slatedb_ffi_fn_free_db(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_BEGIN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_BEGIN
uint64_t uniffi_slatedb_ffi_fn_method_db_begin(void* ptr, RustBuffer isolation_level
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_DELETE
uint64_t uniffi_slatedb_ffi_fn_method_db_delete(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_DELETE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_DELETE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_delete_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_FLUSH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_FLUSH
uint64_t uniffi_slatedb_ffi_fn_method_db_flush(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_FLUSH_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_FLUSH_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_flush_with_options(void* ptr, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET
uint64_t uniffi_slatedb_ffi_fn_method_db_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET_KEY_VALUE
uint64_t uniffi_slatedb_ffi_fn_method_db_get_key_value(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET_KEY_VALUE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_get_key_value_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_MERGE
uint64_t uniffi_slatedb_ffi_fn_method_db_merge(void* ptr, RustBuffer key, RustBuffer operand
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_MERGE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_merge_with_options(void* ptr, RustBuffer key, RustBuffer operand, RustBuffer merge_options, RustBuffer write_options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_METRICS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_METRICS
RustBuffer uniffi_slatedb_ffi_fn_method_db_metrics(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_PUT
uint64_t uniffi_slatedb_ffi_fn_method_db_put(void* ptr, RustBuffer key, RustBuffer value
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_PUT_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_put_with_options(void* ptr, RustBuffer key, RustBuffer value, RustBuffer put_options, RustBuffer write_options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_db_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_db_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SHUTDOWN
uint64_t uniffi_slatedb_ffi_fn_method_db_shutdown(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_SNAPSHOT
uint64_t uniffi_slatedb_ffi_fn_method_db_snapshot(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_STATUS
void uniffi_slatedb_ffi_fn_method_db_status(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_WRITE
uint64_t uniffi_slatedb_ffi_fn_method_db_write(void* ptr, void* batch
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_WRITE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DB_WRITE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_db_write_with_options(void* ptr, void* batch, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBBUILDER
void* uniffi_slatedb_ffi_fn_clone_dbbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBBUILDER
void uniffi_slatedb_ffi_fn_free_dbbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_DBBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_DBBUILDER_NEW
void* uniffi_slatedb_ffi_fn_constructor_dbbuilder_new(RustBuffer path, void* object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_BUILD
uint64_t uniffi_slatedb_ffi_fn_method_dbbuilder_build(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_DB_CACHE_DISABLED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_DB_CACHE_DISABLED
void uniffi_slatedb_ffi_fn_method_dbbuilder_with_db_cache_disabled(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_MERGE_OPERATOR
void uniffi_slatedb_ffi_fn_method_dbbuilder_with_merge_operator(void* ptr, void* merge_operator, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_SEED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_SEED
void uniffi_slatedb_ffi_fn_method_dbbuilder_with_seed(void* ptr, uint64_t seed, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_SETTINGS
void uniffi_slatedb_ffi_fn_method_dbbuilder_with_settings(void* ptr, void* settings, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_SST_BLOCK_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_SST_BLOCK_SIZE
void uniffi_slatedb_ffi_fn_method_dbbuilder_with_sst_block_size(void* ptr, RustBuffer sst_block_size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBBUILDER_WITH_WAL_OBJECT_STORE
void uniffi_slatedb_ffi_fn_method_dbbuilder_with_wal_object_store(void* ptr, void* wal_object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBITERATOR
void* uniffi_slatedb_ffi_fn_clone_dbiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBITERATOR
void uniffi_slatedb_ffi_fn_free_dbiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBITERATOR_NEXT
uint64_t uniffi_slatedb_ffi_fn_method_dbiterator_next(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBITERATOR_SEEK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBITERATOR_SEEK
uint64_t uniffi_slatedb_ffi_fn_method_dbiterator_seek(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBREADER
void* uniffi_slatedb_ffi_fn_clone_dbreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBREADER
void uniffi_slatedb_ffi_fn_free_dbreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_GET
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADER_SHUTDOWN
uint64_t uniffi_slatedb_ffi_fn_method_dbreader_shutdown(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBREADERBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBREADERBUILDER
void* uniffi_slatedb_ffi_fn_clone_dbreaderbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBREADERBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBREADERBUILDER
void uniffi_slatedb_ffi_fn_free_dbreaderbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_DBREADERBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_DBREADERBUILDER_NEW
void* uniffi_slatedb_ffi_fn_constructor_dbreaderbuilder_new(RustBuffer path, void* object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_BUILD
uint64_t uniffi_slatedb_ffi_fn_method_dbreaderbuilder_build(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_CHECKPOINT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_CHECKPOINT_ID
void uniffi_slatedb_ffi_fn_method_dbreaderbuilder_with_checkpoint_id(void* ptr, RustBuffer checkpoint_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_MERGE_OPERATOR
void uniffi_slatedb_ffi_fn_method_dbreaderbuilder_with_merge_operator(void* ptr, void* merge_operator, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_OPTIONS
void uniffi_slatedb_ffi_fn_method_dbreaderbuilder_with_options(void* ptr, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBREADERBUILDER_WITH_WAL_OBJECT_STORE
void uniffi_slatedb_ffi_fn_method_dbreaderbuilder_with_wal_object_store(void* ptr, void* wal_object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBSNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBSNAPSHOT
void* uniffi_slatedb_ffi_fn_clone_dbsnapshot(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBSNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBSNAPSHOT
void uniffi_slatedb_ffi_fn_free_dbsnapshot(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET_KEY_VALUE
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_get_key_value(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_get_key_value_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBSNAPSHOT_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbsnapshot_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBTRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_DBTRANSACTION
void* uniffi_slatedb_ffi_fn_clone_dbtransaction(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBTRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_DBTRANSACTION
void uniffi_slatedb_ffi_fn_free_dbtransaction(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_COMMIT
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_commit(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_COMMIT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_COMMIT_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_commit_with_options(void* ptr, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_DELETE
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_delete(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET_KEY_VALUE
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_get_key_value(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_get_key_value_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_ID
RustBuffer uniffi_slatedb_ffi_fn_method_dbtransaction_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_MARK_READ
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_MARK_READ
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_mark_read(void* ptr, RustBuffer keys
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_MERGE
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_merge(void* ptr, RustBuffer key, RustBuffer operand
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_MERGE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_merge_with_options(void* ptr, RustBuffer key, RustBuffer operand, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_PUT
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_put(void* ptr, RustBuffer key, RustBuffer value
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_PUT_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_put_with_options(void* ptr, RustBuffer key, RustBuffer value, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_ROLLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_ROLLBACK
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_rollback(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SEQNUM
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_SEQNUM
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_seqnum(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_UNMARK_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_DBTRANSACTION_UNMARK_WRITE
uint64_t uniffi_slatedb_ffi_fn_method_dbtransaction_unmark_write(void* ptr, RustBuffer keys
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_LOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_LOGCALLBACK
void* uniffi_slatedb_ffi_fn_clone_logcallback(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_LOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_LOGCALLBACK
void uniffi_slatedb_ffi_fn_free_logcallback(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_LOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_LOGCALLBACK
void uniffi_slatedb_ffi_fn_init_callback_vtable_logcallback(UniffiVTableCallbackInterfaceLogCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_LOGCALLBACK_LOG
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_LOGCALLBACK_LOG
void uniffi_slatedb_ffi_fn_method_logcallback_log(void* ptr, RustBuffer record, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_MERGEOPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_MERGEOPERATOR
void* uniffi_slatedb_ffi_fn_clone_mergeoperator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_MERGEOPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_MERGEOPERATOR
void uniffi_slatedb_ffi_fn_free_mergeoperator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_MERGEOPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_MERGEOPERATOR
void uniffi_slatedb_ffi_fn_init_callback_vtable_mergeoperator(UniffiVTableCallbackInterfaceMergeOperator* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_MERGEOPERATOR_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_MERGEOPERATOR_MERGE
RustBuffer uniffi_slatedb_ffi_fn_method_mergeoperator_merge(void* ptr, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_OBJECTSTORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_OBJECTSTORE
void* uniffi_slatedb_ffi_fn_clone_objectstore(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_OBJECTSTORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_OBJECTSTORE
void uniffi_slatedb_ffi_fn_free_objectstore(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_OBJECTSTORE_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_OBJECTSTORE_FROM_ENV
void* uniffi_slatedb_ffi_fn_constructor_objectstore_from_env(RustBuffer env_file, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_OBJECTSTORE_RESOLVE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_OBJECTSTORE_RESOLVE
void* uniffi_slatedb_ffi_fn_constructor_objectstore_resolve(RustBuffer url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_SETTINGS
void* uniffi_slatedb_ffi_fn_clone_settings(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_SETTINGS
void uniffi_slatedb_ffi_fn_free_settings(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_DEFAULT
void* uniffi_slatedb_ffi_fn_constructor_settings_default(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_ENV
void* uniffi_slatedb_ffi_fn_constructor_settings_from_env(RustBuffer prefix, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_ENV_WITH_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_ENV_WITH_DEFAULT
void* uniffi_slatedb_ffi_fn_constructor_settings_from_env_with_default(RustBuffer prefix, void* default_settings, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_FILE
void* uniffi_slatedb_ffi_fn_constructor_settings_from_file(RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_FROM_JSON_STRING
void* uniffi_slatedb_ffi_fn_constructor_settings_from_json_string(RustBuffer json, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_LOAD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_SETTINGS_LOAD
void* uniffi_slatedb_ffi_fn_constructor_settings_load(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_SETTINGS_SET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_SETTINGS_SET
void uniffi_slatedb_ffi_fn_method_settings_set(void* ptr, RustBuffer key, RustBuffer value_json, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_SETTINGS_TO_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_SETTINGS_TO_JSON_STRING
RustBuffer uniffi_slatedb_ffi_fn_method_settings_to_json_string(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WALFILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WALFILE
void* uniffi_slatedb_ffi_fn_clone_walfile(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WALFILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WALFILE
void uniffi_slatedb_ffi_fn_free_walfile(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_ID
uint64_t uniffi_slatedb_ffi_fn_method_walfile_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_ITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_ITERATOR
uint64_t uniffi_slatedb_ffi_fn_method_walfile_iterator(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_METADATA
uint64_t uniffi_slatedb_ffi_fn_method_walfile_metadata(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_NEXT_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_NEXT_FILE
void* uniffi_slatedb_ffi_fn_method_walfile_next_file(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_NEXT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_NEXT_ID
uint64_t uniffi_slatedb_ffi_fn_method_walfile_next_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILE_SHUTDOWN
void uniffi_slatedb_ffi_fn_method_walfile_shutdown(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WALFILEITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WALFILEITERATOR
void* uniffi_slatedb_ffi_fn_clone_walfileiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WALFILEITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WALFILEITERATOR
void uniffi_slatedb_ffi_fn_free_walfileiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILEITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILEITERATOR_NEXT
uint64_t uniffi_slatedb_ffi_fn_method_walfileiterator_next(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILEITERATOR_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALFILEITERATOR_SHUTDOWN
void uniffi_slatedb_ffi_fn_method_walfileiterator_shutdown(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WALREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WALREADER
void* uniffi_slatedb_ffi_fn_clone_walreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WALREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WALREADER
void uniffi_slatedb_ffi_fn_free_walreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_WALREADER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_WALREADER_NEW
void* uniffi_slatedb_ffi_fn_constructor_walreader_new(RustBuffer path, void* object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALREADER_GET
void* uniffi_slatedb_ffi_fn_method_walreader_get(void* ptr, uint64_t id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALREADER_LIST
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALREADER_LIST
uint64_t uniffi_slatedb_ffi_fn_method_walreader_list(void* ptr, RustBuffer start_id, RustBuffer end_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALREADER_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WALREADER_SHUTDOWN
void uniffi_slatedb_ffi_fn_method_walreader_shutdown(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WRITEBATCH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_WRITEBATCH
void* uniffi_slatedb_ffi_fn_clone_writebatch(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WRITEBATCH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_WRITEBATCH
void uniffi_slatedb_ffi_fn_free_writebatch(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_WRITEBATCH_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_WRITEBATCH_NEW
void* uniffi_slatedb_ffi_fn_constructor_writebatch_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_DELETE
void uniffi_slatedb_ffi_fn_method_writebatch_delete(void* ptr, RustBuffer key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_MERGE
void uniffi_slatedb_ffi_fn_method_writebatch_merge(void* ptr, RustBuffer key, RustBuffer operand, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_MERGE_WITH_OPTIONS
void uniffi_slatedb_ffi_fn_method_writebatch_merge_with_options(void* ptr, RustBuffer key, RustBuffer operand, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_PUT
void uniffi_slatedb_ffi_fn_method_writebatch_put(void* ptr, RustBuffer key, RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_WRITEBATCH_PUT_WITH_OPTIONS
void uniffi_slatedb_ffi_fn_method_writebatch_put_with_options(void* ptr, RustBuffer key, RustBuffer value, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FUNC_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FUNC_INIT_LOGGING
void uniffi_slatedb_ffi_fn_func_init_logging(RustBuffer level, RustBuffer callback, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_slatedb_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_slatedb_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FREE
void ffi_slatedb_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_slatedb_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U8
void ffi_slatedb_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U8
void ffi_slatedb_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U8
void ffi_slatedb_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_slatedb_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I8
void ffi_slatedb_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I8
void ffi_slatedb_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I8
void ffi_slatedb_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_slatedb_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U16
void ffi_slatedb_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U16
void ffi_slatedb_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U16
void ffi_slatedb_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_slatedb_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I16
void ffi_slatedb_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I16
void ffi_slatedb_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I16
void ffi_slatedb_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_slatedb_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U32
void ffi_slatedb_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U32
void ffi_slatedb_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U32
void ffi_slatedb_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_slatedb_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I32
void ffi_slatedb_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I32
void ffi_slatedb_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I32
void ffi_slatedb_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_slatedb_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U64
void ffi_slatedb_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U64
void ffi_slatedb_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U64
void ffi_slatedb_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_slatedb_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I64
void ffi_slatedb_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I64
void ffi_slatedb_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I64
void ffi_slatedb_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_slatedb_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F32
void ffi_slatedb_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F32
void ffi_slatedb_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F32
void ffi_slatedb_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_slatedb_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F64
void ffi_slatedb_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F64
void ffi_slatedb_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F64
void ffi_slatedb_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_slatedb_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_POINTER
void ffi_slatedb_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_slatedb_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_POINTER
void ffi_slatedb_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_POINTER
void* ffi_slatedb_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_slatedb_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_slatedb_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_slatedb_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_slatedb_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_VOID
void ffi_slatedb_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_slatedb_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_VOID
void ffi_slatedb_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_slatedb_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_FUNC_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_FUNC_INIT_LOGGING
uint16_t uniffi_slatedb_ffi_checksum_func_init_logging(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_BEGIN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_BEGIN
uint16_t uniffi_slatedb_ffi_checksum_method_db_begin(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_DELETE
uint16_t uniffi_slatedb_ffi_checksum_method_db_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_DELETE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_DELETE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_delete_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_FLUSH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_FLUSH
uint16_t uniffi_slatedb_ffi_checksum_method_db_flush(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_FLUSH_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_FLUSH_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_flush_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET
uint16_t uniffi_slatedb_ffi_checksum_method_db_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET_KEY_VALUE
uint16_t uniffi_slatedb_ffi_checksum_method_db_get_key_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET_KEY_VALUE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_get_key_value_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_db_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_MERGE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_merge_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_METRICS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_METRICS
uint16_t uniffi_slatedb_ffi_checksum_method_db_metrics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_PUT
uint16_t uniffi_slatedb_ffi_checksum_method_db_put(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_PUT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_put_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_db_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_db_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SHUTDOWN
uint16_t uniffi_slatedb_ffi_checksum_method_db_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_SNAPSHOT
uint16_t uniffi_slatedb_ffi_checksum_method_db_snapshot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_STATUS
uint16_t uniffi_slatedb_ffi_checksum_method_db_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_WRITE
uint16_t uniffi_slatedb_ffi_checksum_method_db_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_WRITE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DB_WRITE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_db_write_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_BUILD
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_DB_CACHE_DISABLED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_DB_CACHE_DISABLED
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_with_db_cache_disabled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_MERGE_OPERATOR
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_with_merge_operator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_SEED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_SEED
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_with_seed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_SETTINGS
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_with_settings(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_SST_BLOCK_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_SST_BLOCK_SIZE
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_with_sst_block_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBBUILDER_WITH_WAL_OBJECT_STORE
uint16_t uniffi_slatedb_ffi_checksum_method_dbbuilder_with_wal_object_store(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBITERATOR_NEXT
uint16_t uniffi_slatedb_ffi_checksum_method_dbiterator_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBITERATOR_SEEK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBITERATOR_SEEK
uint16_t uniffi_slatedb_ffi_checksum_method_dbiterator_seek(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_GET
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADER_SHUTDOWN
uint16_t uniffi_slatedb_ffi_checksum_method_dbreader_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_BUILD
uint16_t uniffi_slatedb_ffi_checksum_method_dbreaderbuilder_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_CHECKPOINT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_CHECKPOINT_ID
uint16_t uniffi_slatedb_ffi_checksum_method_dbreaderbuilder_with_checkpoint_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_MERGE_OPERATOR
uint16_t uniffi_slatedb_ffi_checksum_method_dbreaderbuilder_with_merge_operator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbreaderbuilder_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBREADERBUILDER_WITH_WAL_OBJECT_STORE
uint16_t uniffi_slatedb_ffi_checksum_method_dbreaderbuilder_with_wal_object_store(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET_KEY_VALUE
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_get_key_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_get_key_value_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBSNAPSHOT_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbsnapshot_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_COMMIT
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_commit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_COMMIT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_COMMIT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_commit_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_DELETE
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET_KEY_VALUE
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_get_key_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_get_key_value_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_ID
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_MARK_READ
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_MARK_READ
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_mark_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_MERGE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_merge_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_PUT
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_put(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_PUT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_put_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_ROLLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_ROLLBACK
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_rollback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SEQNUM
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_SEQNUM
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_seqnum(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_UNMARK_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_DBTRANSACTION_UNMARK_WRITE
uint16_t uniffi_slatedb_ffi_checksum_method_dbtransaction_unmark_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_LOGCALLBACK_LOG
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_LOGCALLBACK_LOG
uint16_t uniffi_slatedb_ffi_checksum_method_logcallback_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_MERGEOPERATOR_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_MERGEOPERATOR_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_mergeoperator_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_SETTINGS_SET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_SETTINGS_SET
uint16_t uniffi_slatedb_ffi_checksum_method_settings_set(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_SETTINGS_TO_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_SETTINGS_TO_JSON_STRING
uint16_t uniffi_slatedb_ffi_checksum_method_settings_to_json_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_ID
uint16_t uniffi_slatedb_ffi_checksum_method_walfile_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_ITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_ITERATOR
uint16_t uniffi_slatedb_ffi_checksum_method_walfile_iterator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_METADATA
uint16_t uniffi_slatedb_ffi_checksum_method_walfile_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_NEXT_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_NEXT_FILE
uint16_t uniffi_slatedb_ffi_checksum_method_walfile_next_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_NEXT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_NEXT_ID
uint16_t uniffi_slatedb_ffi_checksum_method_walfile_next_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILE_SHUTDOWN
uint16_t uniffi_slatedb_ffi_checksum_method_walfile_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILEITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILEITERATOR_NEXT
uint16_t uniffi_slatedb_ffi_checksum_method_walfileiterator_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILEITERATOR_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALFILEITERATOR_SHUTDOWN
uint16_t uniffi_slatedb_ffi_checksum_method_walfileiterator_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALREADER_GET
uint16_t uniffi_slatedb_ffi_checksum_method_walreader_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALREADER_LIST
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALREADER_LIST
uint16_t uniffi_slatedb_ffi_checksum_method_walreader_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALREADER_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WALREADER_SHUTDOWN
uint16_t uniffi_slatedb_ffi_checksum_method_walreader_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_DELETE
uint16_t uniffi_slatedb_ffi_checksum_method_writebatch_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_writebatch_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_MERGE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_writebatch_merge_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_PUT
uint16_t uniffi_slatedb_ffi_checksum_method_writebatch_put(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_WRITEBATCH_PUT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_writebatch_put_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_DBBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_DBBUILDER_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_dbbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_DBREADERBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_DBREADERBUILDER_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_dbreaderbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_OBJECTSTORE_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_OBJECTSTORE_FROM_ENV
uint16_t uniffi_slatedb_ffi_checksum_constructor_objectstore_from_env(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_OBJECTSTORE_RESOLVE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_OBJECTSTORE_RESOLVE
uint16_t uniffi_slatedb_ffi_checksum_constructor_objectstore_resolve(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_DEFAULT
uint16_t uniffi_slatedb_ffi_checksum_constructor_settings_default(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_ENV
uint16_t uniffi_slatedb_ffi_checksum_constructor_settings_from_env(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_ENV_WITH_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_ENV_WITH_DEFAULT
uint16_t uniffi_slatedb_ffi_checksum_constructor_settings_from_env_with_default(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_FILE
uint16_t uniffi_slatedb_ffi_checksum_constructor_settings_from_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_FROM_JSON_STRING
uint16_t uniffi_slatedb_ffi_checksum_constructor_settings_from_json_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_LOAD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_SETTINGS_LOAD
uint16_t uniffi_slatedb_ffi_checksum_constructor_settings_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_WALREADER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_WALREADER_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_walreader_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_WRITEBATCH_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_WRITEBATCH_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_writebatch_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_slatedb_ffi_uniffi_contract_version(void
    
);
#endif

 void slatedb_ffi_cgo_dispatchCallbackInterfaceLogCallbackMethod0(uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus );
 void slatedb_ffi_cgo_dispatchCallbackInterfaceLogCallbackFree(uint64_t handle);
 void slatedb_ffi_cgo_dispatchCallbackInterfaceMergeOperatorMethod0(uint64_t uniffi_handle, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void slatedb_ffi_cgo_dispatchCallbackInterfaceMergeOperatorFree(uint64_t handle);

void slatedb_uniffiFutureContinuationCallback(uint64_t, int8_t);
void slatedb_uniffiFreeGorutine(uint64_t);
