

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_LOG_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_LOG_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceFfiLogCallbackMethod0)(uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFfiLogCallbackMethod0(
				UniffiCallbackInterfaceFfiLogCallbackMethod0 cb, uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, record, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_MERGE_OPERATOR_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_MERGE_OPERATOR_METHOD0
typedef void (*UniffiCallbackInterfaceFfiMergeOperatorMethod0)(uint64_t uniffi_handle, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFfiMergeOperatorMethod0(
				UniffiCallbackInterfaceFfiMergeOperatorMethod0 cb, uint64_t uniffi_handle, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, key, existing_value, operand, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_LOG_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_LOG_CALLBACK
typedef struct UniffiVTableCallbackInterfaceFfiLogCallback {
    UniffiCallbackInterfaceFfiLogCallbackMethod0 log;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceFfiLogCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_MERGE_OPERATOR
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_MERGE_OPERATOR
typedef struct UniffiVTableCallbackInterfaceFfiMergeOperator {
    UniffiCallbackInterfaceFfiMergeOperatorMethod0 merge;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceFfiMergeOperator;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDB
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDB
void* uniffi_slatedb_ffi_fn_clone_ffidb(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDB
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDB
void uniffi_slatedb_ffi_fn_free_ffidb(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_BEGIN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_BEGIN
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_begin(void* ptr, RustBuffer isolation_level
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_DELETE
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_delete(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_DELETE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_DELETE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_delete_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_FLUSH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_FLUSH
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_flush(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_FLUSH_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_FLUSH_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_flush_with_options(void* ptr, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET_KEY_VALUE
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_get_key_value(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET_KEY_VALUE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_get_key_value_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_MERGE
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_merge(void* ptr, RustBuffer key, RustBuffer operand
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_MERGE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_merge_with_options(void* ptr, RustBuffer key, RustBuffer operand, RustBuffer merge_options, RustBuffer write_options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_METRICS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_METRICS
RustBuffer uniffi_slatedb_ffi_fn_method_ffidb_metrics(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_PUT
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_put(void* ptr, RustBuffer key, RustBuffer value
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_PUT_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_put_with_options(void* ptr, RustBuffer key, RustBuffer value, RustBuffer put_options, RustBuffer write_options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SHUTDOWN
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_shutdown(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_SNAPSHOT
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_snapshot(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_STATUS
void uniffi_slatedb_ffi_fn_method_ffidb_status(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_WRITE
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_write(void* ptr, void* batch
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_WRITE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDB_WRITE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidb_write_with_options(void* ptr, void* batch, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBBUILDER
void* uniffi_slatedb_ffi_fn_clone_ffidbbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBBUILDER
void uniffi_slatedb_ffi_fn_free_ffidbbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIDBBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIDBBUILDER_NEW
void* uniffi_slatedb_ffi_fn_constructor_ffidbbuilder_new(RustBuffer path, void* object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_BUILD
uint64_t uniffi_slatedb_ffi_fn_method_ffidbbuilder_build(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_DB_CACHE_DISABLED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_DB_CACHE_DISABLED
void uniffi_slatedb_ffi_fn_method_ffidbbuilder_with_db_cache_disabled(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_MERGE_OPERATOR
void uniffi_slatedb_ffi_fn_method_ffidbbuilder_with_merge_operator(void* ptr, void* merge_operator, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_SEED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_SEED
void uniffi_slatedb_ffi_fn_method_ffidbbuilder_with_seed(void* ptr, uint64_t seed, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_SETTINGS
void uniffi_slatedb_ffi_fn_method_ffidbbuilder_with_settings(void* ptr, void* settings, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_SST_BLOCK_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_SST_BLOCK_SIZE
void uniffi_slatedb_ffi_fn_method_ffidbbuilder_with_sst_block_size(void* ptr, RustBuffer sst_block_size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBBUILDER_WITH_WAL_OBJECT_STORE
void uniffi_slatedb_ffi_fn_method_ffidbbuilder_with_wal_object_store(void* ptr, void* wal_object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBITERATOR
void* uniffi_slatedb_ffi_fn_clone_ffidbiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBITERATOR
void uniffi_slatedb_ffi_fn_free_ffidbiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBITERATOR_NEXT
uint64_t uniffi_slatedb_ffi_fn_method_ffidbiterator_next(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBITERATOR_SEEK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBITERATOR_SEEK
uint64_t uniffi_slatedb_ffi_fn_method_ffidbiterator_seek(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBREADER
void* uniffi_slatedb_ffi_fn_clone_ffidbreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBREADER
void uniffi_slatedb_ffi_fn_free_ffidbreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_CLOSE
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_close(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_GET
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADER_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreader_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBREADERBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBREADERBUILDER
void* uniffi_slatedb_ffi_fn_clone_ffidbreaderbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBREADERBUILDER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBREADERBUILDER
void uniffi_slatedb_ffi_fn_free_ffidbreaderbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIDBREADERBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIDBREADERBUILDER_NEW
void* uniffi_slatedb_ffi_fn_constructor_ffidbreaderbuilder_new(RustBuffer path, void* object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_BUILD
uint64_t uniffi_slatedb_ffi_fn_method_ffidbreaderbuilder_build(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_CHECKPOINT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_CHECKPOINT_ID
void uniffi_slatedb_ffi_fn_method_ffidbreaderbuilder_with_checkpoint_id(void* ptr, RustBuffer checkpoint_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_MERGE_OPERATOR
void uniffi_slatedb_ffi_fn_method_ffidbreaderbuilder_with_merge_operator(void* ptr, void* merge_operator, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_OPTIONS
void uniffi_slatedb_ffi_fn_method_ffidbreaderbuilder_with_options(void* ptr, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBREADERBUILDER_WITH_WAL_OBJECT_STORE
void uniffi_slatedb_ffi_fn_method_ffidbreaderbuilder_with_wal_object_store(void* ptr, void* wal_object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBSNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBSNAPSHOT
void* uniffi_slatedb_ffi_fn_clone_ffidbsnapshot(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBSNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBSNAPSHOT
void uniffi_slatedb_ffi_fn_free_ffidbsnapshot(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_get_key_value(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_get_key_value_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBSNAPSHOT_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbsnapshot_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBTRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIDBTRANSACTION
void* uniffi_slatedb_ffi_fn_clone_ffidbtransaction(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBTRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIDBTRANSACTION
void uniffi_slatedb_ffi_fn_free_ffidbtransaction(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_COMMIT
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_commit(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_COMMIT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_COMMIT_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_commit_with_options(void* ptr, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_DELETE
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_delete(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_get(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_get_key_value(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_get_key_value_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_GET_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_get_with_options(void* ptr, RustBuffer key, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_ID
RustBuffer uniffi_slatedb_ffi_fn_method_ffidbtransaction_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_MARK_READ
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_MARK_READ
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_mark_read(void* ptr, RustBuffer keys
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_MERGE
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_merge(void* ptr, RustBuffer key, RustBuffer operand
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_MERGE_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_merge_with_options(void* ptr, RustBuffer key, RustBuffer operand, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_PUT
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_put(void* ptr, RustBuffer key, RustBuffer value
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_PUT_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_put_with_options(void* ptr, RustBuffer key, RustBuffer value, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_ROLLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_ROLLBACK
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_rollback(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_scan(void* ptr, RustBuffer range
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN_PREFIX
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_scan_prefix(void* ptr, RustBuffer prefix
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_scan_prefix_with_options(void* ptr, RustBuffer prefix, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SCAN_WITH_OPTIONS
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_scan_with_options(void* ptr, RustBuffer range, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SEQNUM
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_SEQNUM
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_seqnum(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_UNMARK_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIDBTRANSACTION_UNMARK_WRITE
uint64_t uniffi_slatedb_ffi_fn_method_ffidbtransaction_unmark_write(void* ptr, RustBuffer keys
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFILOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFILOGCALLBACK
void* uniffi_slatedb_ffi_fn_clone_ffilogcallback(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFILOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFILOGCALLBACK
void uniffi_slatedb_ffi_fn_free_ffilogcallback(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_FFILOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_FFILOGCALLBACK
void uniffi_slatedb_ffi_fn_init_callback_vtable_ffilogcallback(UniffiVTableCallbackInterfaceFfiLogCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFILOGCALLBACK_LOG
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFILOGCALLBACK_LOG
void uniffi_slatedb_ffi_fn_method_ffilogcallback_log(void* ptr, RustBuffer record, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIMERGEOPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIMERGEOPERATOR
void* uniffi_slatedb_ffi_fn_clone_ffimergeoperator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIMERGEOPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIMERGEOPERATOR
void uniffi_slatedb_ffi_fn_free_ffimergeoperator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_FFIMERGEOPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_INIT_CALLBACK_VTABLE_FFIMERGEOPERATOR
void uniffi_slatedb_ffi_fn_init_callback_vtable_ffimergeoperator(UniffiVTableCallbackInterfaceFfiMergeOperator* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIMERGEOPERATOR_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIMERGEOPERATOR_MERGE
RustBuffer uniffi_slatedb_ffi_fn_method_ffimergeoperator_merge(void* ptr, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIOBJECTSTORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIOBJECTSTORE
void* uniffi_slatedb_ffi_fn_clone_ffiobjectstore(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIOBJECTSTORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIOBJECTSTORE
void uniffi_slatedb_ffi_fn_free_ffiobjectstore(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIOBJECTSTORE_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIOBJECTSTORE_FROM_ENV
void* uniffi_slatedb_ffi_fn_constructor_ffiobjectstore_from_env(RustBuffer env_file, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIOBJECTSTORE_RESOLVE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIOBJECTSTORE_RESOLVE
void* uniffi_slatedb_ffi_fn_constructor_ffiobjectstore_resolve(RustBuffer url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFISETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFISETTINGS
void* uniffi_slatedb_ffi_fn_clone_ffisettings(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFISETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFISETTINGS
void uniffi_slatedb_ffi_fn_free_ffisettings(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_DEFAULT
void* uniffi_slatedb_ffi_fn_constructor_ffisettings_default(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_ENV
void* uniffi_slatedb_ffi_fn_constructor_ffisettings_from_env(RustBuffer prefix, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_ENV_WITH_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_ENV_WITH_DEFAULT
void* uniffi_slatedb_ffi_fn_constructor_ffisettings_from_env_with_default(RustBuffer prefix, void* default_settings, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_FILE
void* uniffi_slatedb_ffi_fn_constructor_ffisettings_from_file(RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_FROM_JSON_STRING
void* uniffi_slatedb_ffi_fn_constructor_ffisettings_from_json_string(RustBuffer json, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_LOAD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFISETTINGS_LOAD
void* uniffi_slatedb_ffi_fn_constructor_ffisettings_load(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFISETTINGS_SET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFISETTINGS_SET
void uniffi_slatedb_ffi_fn_method_ffisettings_set(void* ptr, RustBuffer key, RustBuffer value_json, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFISETTINGS_TO_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFISETTINGS_TO_JSON_STRING
RustBuffer uniffi_slatedb_ffi_fn_method_ffisettings_to_json_string(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWALFILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWALFILE
void* uniffi_slatedb_ffi_fn_clone_ffiwalfile(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWALFILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWALFILE
void uniffi_slatedb_ffi_fn_free_ffiwalfile(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_CLOSE
void uniffi_slatedb_ffi_fn_method_ffiwalfile_close(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_ID
uint64_t uniffi_slatedb_ffi_fn_method_ffiwalfile_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_ITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_ITERATOR
uint64_t uniffi_slatedb_ffi_fn_method_ffiwalfile_iterator(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_METADATA
uint64_t uniffi_slatedb_ffi_fn_method_ffiwalfile_metadata(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_NEXT_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_NEXT_FILE
void* uniffi_slatedb_ffi_fn_method_ffiwalfile_next_file(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_NEXT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILE_NEXT_ID
uint64_t uniffi_slatedb_ffi_fn_method_ffiwalfile_next_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWALFILEITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWALFILEITERATOR
void* uniffi_slatedb_ffi_fn_clone_ffiwalfileiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWALFILEITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWALFILEITERATOR
void uniffi_slatedb_ffi_fn_free_ffiwalfileiterator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILEITERATOR_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILEITERATOR_CLOSE
void uniffi_slatedb_ffi_fn_method_ffiwalfileiterator_close(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILEITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALFILEITERATOR_NEXT
uint64_t uniffi_slatedb_ffi_fn_method_ffiwalfileiterator_next(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWALREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWALREADER
void* uniffi_slatedb_ffi_fn_clone_ffiwalreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWALREADER
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWALREADER
void uniffi_slatedb_ffi_fn_free_ffiwalreader(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIWALREADER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIWALREADER_NEW
void* uniffi_slatedb_ffi_fn_constructor_ffiwalreader_new(RustBuffer path, void* object_store, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALREADER_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALREADER_CLOSE
void uniffi_slatedb_ffi_fn_method_ffiwalreader_close(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALREADER_GET
void* uniffi_slatedb_ffi_fn_method_ffiwalreader_get(void* ptr, uint64_t id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALREADER_LIST
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWALREADER_LIST
uint64_t uniffi_slatedb_ffi_fn_method_ffiwalreader_list(void* ptr, RustBuffer start_id, RustBuffer end_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWRITEBATCH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CLONE_FFIWRITEBATCH
void* uniffi_slatedb_ffi_fn_clone_ffiwritebatch(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWRITEBATCH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FREE_FFIWRITEBATCH
void uniffi_slatedb_ffi_fn_free_ffiwritebatch(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIWRITEBATCH_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_CONSTRUCTOR_FFIWRITEBATCH_NEW
void* uniffi_slatedb_ffi_fn_constructor_ffiwritebatch_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_DELETE
void uniffi_slatedb_ffi_fn_method_ffiwritebatch_delete(void* ptr, RustBuffer key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_MERGE
void uniffi_slatedb_ffi_fn_method_ffiwritebatch_merge(void* ptr, RustBuffer key, RustBuffer operand, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_MERGE_WITH_OPTIONS
void uniffi_slatedb_ffi_fn_method_ffiwritebatch_merge_with_options(void* ptr, RustBuffer key, RustBuffer operand, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_PUT
void uniffi_slatedb_ffi_fn_method_ffiwritebatch_put(void* ptr, RustBuffer key, RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_METHOD_FFIWRITEBATCH_PUT_WITH_OPTIONS
void uniffi_slatedb_ffi_fn_method_ffiwritebatch_put_with_options(void* ptr, RustBuffer key, RustBuffer value, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FUNC_FFI_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_FN_FUNC_FFI_INIT_LOGGING
void uniffi_slatedb_ffi_fn_func_ffi_init_logging(RustBuffer level, RustBuffer callback, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_slatedb_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_slatedb_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_FREE
void ffi_slatedb_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_slatedb_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U8
void ffi_slatedb_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U8
void ffi_slatedb_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U8
void ffi_slatedb_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_slatedb_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I8
void ffi_slatedb_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I8
void ffi_slatedb_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I8
void ffi_slatedb_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_slatedb_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U16
void ffi_slatedb_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U16
void ffi_slatedb_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U16
void ffi_slatedb_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_slatedb_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I16
void ffi_slatedb_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I16
void ffi_slatedb_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I16
void ffi_slatedb_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_slatedb_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U32
void ffi_slatedb_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U32
void ffi_slatedb_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U32
void ffi_slatedb_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_slatedb_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I32
void ffi_slatedb_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I32
void ffi_slatedb_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I32
void ffi_slatedb_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_slatedb_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_U64
void ffi_slatedb_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_U64
void ffi_slatedb_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_U64
void ffi_slatedb_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_slatedb_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_I64
void ffi_slatedb_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_I64
void ffi_slatedb_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_I64
void ffi_slatedb_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_slatedb_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F32
void ffi_slatedb_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F32
void ffi_slatedb_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F32
void ffi_slatedb_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_slatedb_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_F64
void ffi_slatedb_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_F64
void ffi_slatedb_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_F64
void ffi_slatedb_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_slatedb_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_POINTER
void ffi_slatedb_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_slatedb_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_POINTER
void ffi_slatedb_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_POINTER
void* ffi_slatedb_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_slatedb_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_slatedb_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_slatedb_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_slatedb_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_POLL_VOID
void ffi_slatedb_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_slatedb_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_FREE_VOID
void ffi_slatedb_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_slatedb_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_FUNC_FFI_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_FUNC_FFI_INIT_LOGGING
uint16_t uniffi_slatedb_ffi_checksum_func_ffi_init_logging(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_BEGIN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_BEGIN
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_begin(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_DELETE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_DELETE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_DELETE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_delete_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_FLUSH
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_FLUSH
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_flush(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_FLUSH_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_FLUSH_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_flush_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET_KEY_VALUE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_get_key_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET_KEY_VALUE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_get_key_value_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_MERGE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_merge_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_METRICS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_METRICS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_metrics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_PUT
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_put(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_PUT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_put_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SHUTDOWN
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_SNAPSHOT
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_snapshot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_STATUS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_WRITE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_WRITE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDB_WRITE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidb_write_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_BUILD
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_DB_CACHE_DISABLED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_DB_CACHE_DISABLED
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_with_db_cache_disabled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_MERGE_OPERATOR
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_with_merge_operator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_SEED
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_SEED
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_with_seed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_SETTINGS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_with_settings(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_SST_BLOCK_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_SST_BLOCK_SIZE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_with_sst_block_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBBUILDER_WITH_WAL_OBJECT_STORE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbbuilder_with_wal_object_store(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBITERATOR_NEXT
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbiterator_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBITERATOR_SEEK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBITERATOR_SEEK
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbiterator_seek(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_CLOSE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_GET
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADER_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreader_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_BUILD
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreaderbuilder_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_CHECKPOINT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_CHECKPOINT_ID
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreaderbuilder_with_checkpoint_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_MERGE_OPERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_MERGE_OPERATOR
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreaderbuilder_with_merge_operator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreaderbuilder_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_WAL_OBJECT_STORE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBREADERBUILDER_WITH_WAL_OBJECT_STORE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbreaderbuilder_with_wal_object_store(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_get_key_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET_KEY_VALUE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_get_key_value_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBSNAPSHOT_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbsnapshot_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_COMMIT
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_commit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_COMMIT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_COMMIT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_commit_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_DELETE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_get_key_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET_KEY_VALUE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_get_key_value_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_GET_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_get_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_ID
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_MARK_READ
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_MARK_READ
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_mark_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_MERGE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_merge_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_PUT
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_put(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_PUT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_put_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_ROLLBACK
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_ROLLBACK
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_rollback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN_PREFIX
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_scan_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN_PREFIX_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_scan_prefix_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SCAN_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_scan_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SEQNUM
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_SEQNUM
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_seqnum(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_UNMARK_WRITE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIDBTRANSACTION_UNMARK_WRITE
uint16_t uniffi_slatedb_ffi_checksum_method_ffidbtransaction_unmark_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFILOGCALLBACK_LOG
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFILOGCALLBACK_LOG
uint16_t uniffi_slatedb_ffi_checksum_method_ffilogcallback_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIMERGEOPERATOR_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIMERGEOPERATOR_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_ffimergeoperator_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFISETTINGS_SET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFISETTINGS_SET
uint16_t uniffi_slatedb_ffi_checksum_method_ffisettings_set(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFISETTINGS_TO_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFISETTINGS_TO_JSON_STRING
uint16_t uniffi_slatedb_ffi_checksum_method_ffisettings_to_json_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_CLOSE
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfile_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_ID
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfile_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_ITERATOR
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_ITERATOR
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfile_iterator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_METADATA
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfile_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_NEXT_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_NEXT_FILE
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfile_next_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_NEXT_ID
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILE_NEXT_ID
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfile_next_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILEITERATOR_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILEITERATOR_CLOSE
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfileiterator_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILEITERATOR_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALFILEITERATOR_NEXT
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalfileiterator_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALREADER_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALREADER_CLOSE
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalreader_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALREADER_GET
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALREADER_GET
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalreader_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALREADER_LIST
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWALREADER_LIST
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwalreader_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_DELETE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_DELETE
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwritebatch_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_MERGE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_MERGE
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwritebatch_merge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_MERGE_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_MERGE_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwritebatch_merge_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_PUT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_PUT
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwritebatch_put(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_PUT_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_METHOD_FFIWRITEBATCH_PUT_WITH_OPTIONS
uint16_t uniffi_slatedb_ffi_checksum_method_ffiwritebatch_put_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIDBBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIDBBUILDER_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffidbbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIDBREADERBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIDBREADERBUILDER_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffidbreaderbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIOBJECTSTORE_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIOBJECTSTORE_FROM_ENV
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffiobjectstore_from_env(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIOBJECTSTORE_RESOLVE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIOBJECTSTORE_RESOLVE
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffiobjectstore_resolve(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_DEFAULT
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffisettings_default(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_ENV
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_ENV
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffisettings_from_env(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_ENV_WITH_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_ENV_WITH_DEFAULT
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffisettings_from_env_with_default(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_FILE
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_FILE
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffisettings_from_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_JSON_STRING
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_FROM_JSON_STRING
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffisettings_from_json_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_LOAD
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFISETTINGS_LOAD
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffisettings_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIWALREADER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIWALREADER_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffiwalreader_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIWRITEBATCH_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLATEDB_FFI_CHECKSUM_CONSTRUCTOR_FFIWRITEBATCH_NEW
uint16_t uniffi_slatedb_ffi_checksum_constructor_ffiwritebatch_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLATEDB_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SLATEDB_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_slatedb_ffi_uniffi_contract_version(void
    
);
#endif

 void slatedb_ffi_cgo_dispatchCallbackInterfaceFfiLogCallbackMethod0(uint64_t uniffi_handle, RustBuffer record, void* uniffi_out_return, RustCallStatus* callStatus );
 void slatedb_ffi_cgo_dispatchCallbackInterfaceFfiLogCallbackFree(uint64_t handle);
 void slatedb_ffi_cgo_dispatchCallbackInterfaceFfiMergeOperatorMethod0(uint64_t uniffi_handle, RustBuffer key, RustBuffer existing_value, RustBuffer operand, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void slatedb_ffi_cgo_dispatchCallbackInterfaceFfiMergeOperatorFree(uint64_t handle);

void slatedb_uniffiFutureContinuationCallback(uint64_t, int8_t);
void slatedb_uniffiFreeGorutine(uint64_t);
